openapi: 3.0.1
info:
  title: Pn-paper-tracker
  termsOfService: https://termofservice.it
  x-api-id: api-paper-tracker-private
  x-summary: OpenAPI servizio Paper tracker
  description: |-
    ## Abstract
      Questo servizio ha il compito di:
        - Ricevere gli aggiornamenti di spedizione provenienti dal sistema pn-external-channels (consolidatore);
        - Validare gli eventi ricevuti;
        - Validare i documenti allegati tramite un servizio OCR/AI;
        - Tracciare ogni singolo tentativo di spedizione verso un destinatario;
        - Inoltrare gli eventi validati al workflow analogico.
  contact:
    email: pn@pagopa.it
  license:
    name: PN software license
    url: https://www.pn.pagopa.it/LICENSE
  version: '1.0.0'

paths:
  /status:
    get:
      summary: healthCheck path
      description: health check path per verificare lo stato del micro servizio
      tags:
        - HealthCheck
      operationId: status
      responses:
        '200':
          description: Ok
        '500':
          description: Internal Server Error
  '/paper-tracker-private/init':
    post:
      summary: Inserimento tracker
      description: >-
        Permette l'inserimento di un evento di tracking restituendo l'entità creata
      tags:
        - TrackingCreation
      operationId: trackingCreation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrackerCreationRequest'
        required: true
      responses:
        '201':
          description: Created - Tracker created
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'

components:
  parameters:
    requestId:
      description: >-
        Request id
      name: requestId
      in: path
      required: true
      schema:
        type: string
        # ASCII printable characters
        pattern: ^[ -~]*$
        maxLength: 1024
    deliveryDriverId:
      description: >-
        Id del recapitista
      name: deliveryDriverId
      in: query
      required: true
      schema:
        type: string
        # ASCII printable characters
        pattern: ^[ -~]*$
        maxLength: 1024

  schemas:
    TrackerCreationRequest:
      type: object
      properties:
        requestId:
          type: string
          description: Identificativo singola richiesta per spedizione analogica
          example: "PREPARE_ANALOG_DOMICILE.IUN_LKHJ-HKGV-HQUP-202402-Q-1.RECINDEX_0.ATTEMPT_0.PCRETRY_0"
        productType:
          type: string
          description: Tipo prodotto
          example: "AR"
        deliveryDriverId:
          type: string
          description: Id recapitista
      required:
        - requestId
        - productType
        - deliveryDriverId

              