package it.pagopa.pn.papertracker.service.handler_step.AR;

import lombok.Getter;

import java.util.List;

@Getter
public enum TestSequenceEnum {
    OK_CONSEGNATO_FASCICOLO_CHIUSO(List.of("RECRN001A", "RECRN001B", "RECRN001C"), List.of("RECRN001B-AR")),
    MANCATA_CONSEGNA_FASCICOLO_CHIUSO(List.of("RECRN002A", "RECRN002B", "RECRN002C"), List.of("RECRN002B-Plico")),
    IRREPERIBILITA_ASSOLUTA_FASCICOLO_CHIUSO(List.of("RECRN002D", "RECRN002E", "RECRN002F"), List.of("RECRN002E-Plico#Indagine")),
    FURTO_SMARRIMENTO_DETERIORAMENTO(List.of("RECRN006"), List.of()),
    INESITO_FURTO_SMARRIMENTO_DETERIORAMENTO(List.of("RECRN010", "RECRN006"), List.of()),
    INESITO_INGIACENZA_FURTO_SMARRIMENTO_DETERIORAMENTO(List.of("RECRN010", "RECRN011", "RECRN006"), List.of()),
    CONSEGNATO_GIACENZA_FASCICOLO_CHIUSO_ALLEGATI_MANCANTI(List.of("RECRN010", "RECRN011", "RECRN003A", "RECRN003B", "RECRN003C"), List.of()),
    CONSEGNATO_GIACENZA_FASCICOLO_CHIUSO(List.of("RECRN010", "RECRN011", "RECRN003A", "RECRN003B", "RECRN003C"), List.of("RECRN003B-AR")),
    MANCATA_CONSEGNA_GIACENZA_FASCICOLO_CHIUSO(List.of("RECRN010", "RECRN011", "RECRN004A", "RECRN004B", "RECRN004C"), List.of("RECRN004B-Plico")),
    COMPIUTA_GIACENZA_GIACENZA_FASCICOLO_CHIUSO(List.of("RECRN010", "RECRN011", "RECRN005A", "RECRN005B", "RECRN005C"), List.of("RECRN005B-Plico")),
    OK_CONSEGNATO_FASCICOLO_CHIUSO_AB_DUPLICATI_OK(List.of("RECRN001A", "RECRN001B", "RECRN001A", "RECRN001B", "RECRN001B", "RECRN001C"), List.of("RECRN001B-AR", "RECRN001B-AR", "RECRN001B-AR")),
    OK_CONSEGNATO_FASCICOLO_CHIUSO_010_DUPLICATO_OK(List.of("RECRN010", "RECRN010", "RECRN011", "RECRN003A", "RECRN003B", "RECRN003C"), List.of("RECRN003B-AR")),
    OK_CONSEGNATO_FASCICOLO_CHIUSO_011_DUPLICATO_OK(List.of("RECRN010", "RECRN011", "RECRN011", "RECRN003A", "RECRN003B", "RECRN003C"), List.of("RECRN003B-AR")),
    CONSEGNATO_FASCICOLO_CHIUSO_STATO_ASSENTE(List.of("RECRN010", "RECRN010", "RECRN003A", "RECRN003B", "RECRN003C"), List.of("RECRN003B-AR")),
    CONSEGNATO_FASCICOLO_CHIUSO_STATO_NON_INERENTE(List.of("RECRN001A", "RECRN002A", "RECRN001B", "RECRN001C"), List.of("RECRN001B-AR")),
    IRREPERIBILITA_ASSOLUTA_FASCICOLO_CHIUSO_STATO_NON_INERENTE(List.of("RECRN010", "RECRN011", "RECRN003A", "RECRN003B", "RECRN004A", "RECRN004B", "RECRN004C"), List.of("RECRN003B-AR", "RECRN004B-Plico")),
    IRREPERIBILITA_ASSOLUTA_FASCICOLO_CHIUSO_ALLEGATI_SEPARATI(List.of("RECRN002D", "RECRN002E", "RECRN002E", "RECRN002F"), List.of("RECRN002E-Plico", "RECRN002E-Indagine")),
    IRREPERIBILITA_ASSOLUTA_FASCICOLO_CHIUSO_ALLEGATI_MANCANTI(List.of("RECRN002D", "RECRN002E", "RECRN002F"), List.of("RECRN002E-Plico"));

    private final List<String> sentDocuments;
    private final List<String> statusCodes;

    TestSequenceEnum(List<String> statusCodes, List<String> sentDocuments) {
        this.sentDocuments = sentDocuments;
        this.statusCodes = statusCodes;
    }
}
