AWSTemplateFormatVersion: 2010-09-09
Description: 'Microservice deploy for pn-paper-tracker'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'
  
  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  EcsLogGroup:
    Type: String
    Description: 'Ecs log group name'

  WireTapLogActivation:
    Type: String
    Default: false
    Description: Activation of wire logs
    AllowedValues:
      - true
      - false

  MountEfs:
    Type: String
    Default: false
    AllowedValues:
      - "true"
      - "false"

  FargateEFSFileSystemID:
    Type: String
    Description: "EFS Filesystem"

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
  CpuValue:
    Type: Number
    Default: 1024
    Description: Fargate virtual CPU quantity 1024 equals one vCPU

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: memory amount reserved to the task pod.
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

  MinTasksNumber:
    Default: 1
    Type: Number
    Description: minimum autoscaling number of tasks

  MaxTasksNumber:
    Default: 1
    Type: Number
    Description: maximum autoscaling number of tasks

  PnCronAnalyzer:
    Type: String
    Default: '-'
    Description: Cron for which you send the metric to CloudWatch

  PnOcrOutputsQueueName:
    Type: String
    Description: 'Name of the SQS queue where OCR outputs are sent'

  PnOcrOutputsQueueARN:
    Type: String
    Description: 'ARN of the SQS queue where OCR outputs are sent'

  PnOcrInputQueueARN:
    Type: String
    Description: 'ARN of the SQS queue where OCR request are sent'

  PnOcrInputQueueUrl:
    Type: String
    Description: 'URL of the SQS queue where OCR request are sent'

  ExternalChannelToPaperTrackerQueueName:
    Type: String
    Description: 'Name of the SQS queue where external channel messages are sent'

  ExternalChannelToPaperTrackerQueueARN:
    Type: String
    Description: 'ARN of the SQS queue where external channel messages are sent'

  PaperTrackingsErrorsTableName:
    Type: String
    Description: 'DynamoDB table name for PaperTrackingsErrors'

  PaperTrackingsErrorsTableArn:
    Type: String
    Description: 'DynamoDB table ARN for PaperTrackingsErrors'


  PaperTrackingsTableName:
    Type: String
    Description: 'DynamoDB table name for PaperTrackings'

  PaperTrackingsTableArn:
    Type: String
    Description: 'DynamoDB table ARN for PaperTrackings'

  PaperTrackerDryRunOutputsTableName:
    Type: String
    Description: 'DynamoDB table name for PaperTrackerDryRunOutputs'

  PaperTrackerDryRunOutputsTableArn:
    Type: String
    Description: 'DynamoDB table ARN for PaperTrackerDryRunOutputs'

  ExternalChannelOutputsQueue:
    Type: String
    Description: 'Name of the SQS queue where external channel outputs are sent'

Resources:

  PaperTrackerMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-paper-tracker'
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        HealthCheckPath: /actuator/health
        EfsFilesystem: !Ref FargateEFSFileSystemID
        MountEfs: !Ref MountEfs
        WireTapLogActivation: !Ref WireTapLogActivation
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        JavaToolOptions: '-XX:MaxDirectMemorySize=256m'
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_CRON_ANALYZER=${PnCronAnalyzer}'
        ContainerEnvEntry3: !Sub 'WIRE_TAP_LOG=${WireTapLogActivation}'
        ContainerEnvEntry4: !Sub 'PN_PAPERTRACKER_DAO_PAPERTRACKERDRYRUNOUTPUTSTABLE=${PaperTrackerDryRunOutputsTableName}'
        ContainerEnvEntry5: !Sub 'PN_PAPERTRACKER_DAO_PAPERTRACKINGSERRORSTABLE=${PaperTrackingsErrorsTableName}'
        ContainerEnvEntry6: !Sub 'PN_PAPERTRACKER_DAO_PAPERTRACKINGSTABLE=${PaperTrackingsTableName}'
        ContainerEnvEntry7: !Sub 'PN_PAPERTRACKER_PAPERCHANNELBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry8: !Sub 'PN_PAPERTRACKER_EXTERNALCHANNELOUTPUTSQUEUE=${ExternalChannelOutputsQueue}'
        MappedPaths: '/paper-tracker/*,/paper-tracker-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        TaskRoleManagedPolicyArn: !Ref PaperTrackerMicroserviceTaskPolicy
        EcsLogGroup: !Ref EcsLogGroup

  PaperTrackerMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-paper-tracker"
        AlarmArns: !Join
          - ','
          - - !GetAtt PaperTrackerMicroservice.Outputs.FatalLogsMetricAlarmArn
        DynamoDBTableNames: !Join
          - ','
          - - !Ref PaperTrackingsTableName
          - - !Ref PaperTrackingsErrorsTableName
          - - !Ref PaperTrackerDryRunOutputsTableName
        LogGroupsNames: !Join
          - ','
          - - !Sub '/aws/ecs/${ProjectName}-paper-tracker'

  PaperTrackerMicroserviceTaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:UpdateItem
            Resource:
              - !Sub "${PaperTrackingsTableArn}"
              - !Sub "${PaperTrackerDryRunOutputsTableArn}"
              - !Sub "${PaperTrackingsErrorsTableArn}"
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - sqs:GetQueueUrl
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Resource:
              - !Ref ExternalChannelToPaperTrackerQueueARN
              - !Ref PnOcrOutputsQueueARN
              - !Ref PnOcrInputQueueARN
