AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

  AlarmSNSTopicName:
    Type: String

Resources:
  PnPaperTrackerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-paper-tracker'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  PaperTrackingsErrorsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperTrackingsErrors'
      AttributeDefinitions:
        - AttributeName: "trackingId"
          AttributeType: "S"
        - AttributeName: "created"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "trackingId"
          KeyType: "HASH"
        - AttributeName: "created"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperTrackerDryRunOutputsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperTrackerDryRunOutputs'
      AttributeDefinitions:
        - AttributeName: "trackingId"
          AttributeType: "S"
        - AttributeName: "created"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "trackingId"
          KeyType: "HASH"
        - AttributeName: "created"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperTrackingsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperTrackings'
      AttributeDefinitions:
        - AttributeName: "trackingId"
          AttributeType: "S"
        - AttributeName: "ocrRequestId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "trackingId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "ocrRequestId-index"
          KeySchema:
            - AttributeName: "ocrRequestId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PnOcrOutputsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-ocr_outputs'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 300
        MaxReceiveCount: 10
        DelaySeconds: 1

  ExternalChannelToPaperTrackerQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channel_to_paper_tracker'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 300
        MaxReceiveCount: 10
        DelaySeconds: 1

Outputs:
  EcsLogGroup:
    Value: !GetAtt PnPaperTrackerLogGroup.Outputs.LogGroupName

  PaperTrackingsErrorsTableName:
    Description: Name of dynamodb table containing trackings errors
    Value: !Ref PaperTrackingsErrorsTable
  PaperTrackingsErrorsTableArn:
    Description: ARN of dynamodb table containing trackings errors
    Value: !Sub '${PaperTrackingsErrorsTable.Arn}'

  PaperTrackerDryRunOutputsTableName:
    Description: Name of dynamodb table containing trackings outputs
    Value: !Ref PaperTrackerDryRunOutputsTable
  PaperTrackerDryRunOutputsTableArn:
    Description: ARN of dynamodb table containing trackings outputs
    Value: !Sub '${PaperTrackerDryRunOutputsTable.Arn}'

  PaperTrackingsTableName:
    Description: Name of dynamodb table containing trackings
    Value: !Ref PaperTrackingsTable
  PaperTrackingsTableArn:
    Description: ARN of dynamodb table containing trackings
    Value: !Sub '${PaperTrackingsTable.Arn}'

  PnOcrOutputsQueueName:
    Value: !GetAtt PnOcrOutputsQueue.Outputs.QueueName
  PnOcrOutputsQueueARN:
    Value: !GetAtt PnOcrOutputsQueue.Outputs.QueueARN
  PnOcrOutputsQueueURL:
    Value: !GetAtt PnOcrOutputsQueue.Outputs.QueueURL

  ExternalChannelToPaperTrackerQueueName:
    Value: !GetAtt ExternalChannelToPaperTrackerQueue.Outputs.QueueName
  ExternalChannelToPaperTrackerQueueARN:
    Value: !GetAtt ExternalChannelToPaperTrackerQueue.Outputs.QueueARN

