package it.pagopa.pn.papertracker.service.handler_step.RIR;

import lombok.Getter;

import java.util.List;

@Getter
public enum TestSequenceRirEnum {
    FURTO_SMARRIMENTO_DETERIORAMENTO(List.of("RECRI005"), List.of()),
    FURTO_SMARRIMENTO_DETERIORAMENTO_AVVIATO(List.of("RECRI001", "RECRI005"), List.of()),

    CONSEGNATO_FASCICOLO_CHIUSO(List.of("RECRI001", "RECRI002", "RECRI003A", "RECRI003B", "RECRI003C"), List.of("RECRI003B-AR")),
    CONSEGNATO_FASCICOLO_CHIUSO_STATO_ASSENTE(List.of("RECRI001", "RECRI002", "RECRI003B", "RECRI003C"), List.of("RECRI003B-AR")),
    CONSEGNATO_FASCICOLO_CHIUSO_STATO_DUPLICATO(List.of("RECRI001", "RECRI002", "RECRI003A", "RECRI003B", "RECRI003A", "RECRI003B", "RECRI003C"), List.of("RECRI003B-AR","RECRI003B-AR")),
    CONSEGNATO_FASCICOLO_CHIUSO_STATO_NON_INERENTE(List.of("RECRI001", "RECRI002", "RECRI004B", "RECRI003A", "RECRI003B", "RECRI003C"), List.of("RECRI003B-AR")),
    CONSEGNATO_FASCICOLO_CHIUSO_ALLEGATO_ASSENTE(List.of("RECRI001", "RECRI002", "RECRI003A", "RECRI003B", "RECRI003C"), List.of()),

    NON_CONSEGNATO_FASCICOLO_CHIUSO(List.of("RECRI001", "RECRI002", "RECRI004A", "RECRI004B", "RECRI004C"), List.of("RECRI004B-Plico")),
    NON_CONSEGNATO_FASCICOLO_CHIUSO_STATO_ASSENTE(List.of("RECRI001", "RECRI002", "RECRI004B", "RECRI004C"), List.of("RECRI004B-Plico")),
    NON_CONSEGNATO_FASCICOLO_CHIUSO_STATO_DUPLICATO(List.of("RECRI001", "RECRI002", "RECRI004A", "RECRI004B", "RECRI004A", "RECRI004B", "RECRI004C"), List.of("RECRI004B-Plico", "RECRI004B-Plico")),
    NON_CONSEGNATO_FASCICOLO_CHIUSO_STATO_NON_INERENTE(List.of("RECRI001", "RECRI002", "RECRI003B", "RECRI004A", "RECRI004B", "RECRI004C"), List.of("RECRI004B-Plico")),
    NON_CONSEGNATO_FASCICOLO_CHIUSO_ALLEGATO_ASSENTE(List.of("RECRI001", "RECRI002", "RECRI004A", "RECRI004B", "RECRI004C"), List.of());

    private final List<String> sentDocuments;
    private final List<String> statusCodes;

    TestSequenceRirEnum(List<String> statusCodes, List<String> sentDocuments) {
        this.sentDocuments = sentDocuments;
        this.statusCodes = statusCodes;
    }
}
